<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/uirian/Code/uiriansan.site/static/models/anilist.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { HemisphereLight } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Curve_1: THREE.Mesh
      Curve_2: THREE.Mesh
    }
    materials: {
      AniListA: THREE.MeshStandardMaterial
      AnilistL: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/anilist.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={150} rotation={[1.5, 0, 0]}>
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Curve_1.geometry} material={gltf.materials.AniListA} />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Curve_2.geometry} material={gltf.materials.AnilistL} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
