<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/uirian/Code/uiriansan.site/static/models/cube.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { DEG2RAD } from 'three/src/math/MathUtils.js'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube002: THREE.Mesh
      Cube002_1: THREE.Mesh
    }
    materials: {
      Cube: THREE.MeshStandardMaterial
      Inside: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/cube.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={1} rotation={[0, 90*DEG2RAD, 0]}>
      <T.Mesh geometry={gltf.nodes.Cube002.geometry} material={gltf.materials.Cube} />
      <T.Mesh geometry={gltf.nodes.Cube002_1.geometry} material={gltf.materials.Inside} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
